version: '2'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8000:8000"
    environment:
      SERVER_NAME: mainserver

  
  executionengine:
    build: executionengine/.
    command: node index.js
    environment:
      SERVER_NAME: executionengine
