FROM node:16

WORKDIR /usr/src/app

COPY ./package*.json ./

RUN npm ci --only=production
# if running in production
# RUN npm ci --only=production
RUN npm build
RUN npm install -g serve

COPY . .
EXPOSE 3000

CMD ["serve","-s", "build"]
